### ISSUE TITLE
Problem to run gausssum in Debian 4.19.37

### ISSUE THREAD

**Issue by zoxfuganti** [gausssum/gausssum#10]
I have a problem!
When I'm try to run the gausssum in debian I have this messages: 

[ fuganti@turing ~/softwares/gausssum/GaussSum-3.0.2/GaussSum-3.0.2 ]
> python3.7 ./GaussSum.py
Traceback (most recent call last):
  File "./GaussSum.py", line 23, in <module>
    import gausssum.gausssumgui
  File "/home/fuganti/softwares/gausssum/GaussSum-3.0.2/GaussSum-3.0.2/gausssum/gausssumgui.py", line 29, in <module>
    from gausssum.popanalysis import Popanalysis
  File "/home/fuganti/softwares/gausssum/GaussSum-3.0.2/GaussSum-3.0.2/gausssum/popanalysis.py", line 20, in <module>
    from .plot import DisplayPlot
  File "/home/fuganti/softwares/gausssum/GaussSum-3.0.2/GaussSum-3.0.2/gausssum/plot.py", line 22, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
ImportError: cannot import name 'NavigationToolbar2TkAgg' from 'matplotlib.backends.backend_tkagg' (/usr/lib/python3/dist-packages/matplotlib/backends/backend_tkagg.py)
[ fuganti@turing ~/softwares/gausssum/GaussSum-3.0.2/GaussSum-3.0.2 ]

I try the old versions of the python and the same message appear. This happened after upgrade the debian for the 8.0 and up.
Any solution?

**Comment by spheex** [comment]
I had a similar problem.

I edited the 'plot.py' file by removing the 'Agg' at the end of 'NavigationToolbar2TkAgg' and it properly works!
https://stackoverflow.com/questions/32188180/from-matplotlib-backends-import-tkagg-importerror-cannot-import-name-tkagg
