### ISSUE TITLE
GaussSum error in linux

### ISSUE THREAD

**Issue by serusalta** [gausssum/gausssum#22]
Dear Gausssum developers:
Thanks for developing this software. I'm facing some troubles to execute it on linux. This is what I got when I tried to run it. 
Traceback (most recent call last):
  File "/home/seru/opt/GaussSum-3.0.2/GaussSum.py", line 23, in <module>
    import gausssum.gausssumgui
  File "/home/seru/opt/GaussSum-3.0.2/gausssum/gausssumgui.py", line 27, in <module>
    from gausssum.preferencesbox import PreferencesPopupBox
  File "/home/seru/opt/GaussSum-3.0.2/gausssum/preferencesbox.py", line 21, in <module>
    class PreferencesPopupBox(simpledialog.Dialog):
NameError: name 'simpledialog' is not defined

I could fix this adding import tkinter.simpledialog as simpledialog in gaussumgui.py y preferencesbox.py. 

Then the next error: from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
ImportError: cannot import name 'NavigationToolbar2TkAgg' from 'matplotlib.backends.backend_tkagg' (/home/seru/.local/lib/python3.10/site-packages/matplotlib/backends/backend_tkagg.py)  

These can be fixed by deleting Agg in NavigationToolbar2Tk on plot.py... then I could see the window.. I can open the log file, but when I try to see the pot there's no new window with the plot.

I think that is a problem with the python version... Do you have information about how to fix this?

Thanks in advance,

**Comment by serusalta** [comment]
As I can see is an error in the electrtrans.py when es trying to convert nm to cm-1. Can anyone help me?
Here the messeage:
Traceback (most recent call last):
  File "/home/seru/opt/GaussSum-3.0.2/gausssum/gausssumgui.py", line 416, in runscript
    worked = ET(self.root,self.screen,self.data,self.logfile.filename,int(self.start.get()),int(self.end.get()),int(self.numpts.get()),float(self.FWHM.get()),self.UVplot.get(),self.eddm.get())
  File "/home/seru/opt/GaussSum-3.0.2/gausssum/electrontrans.py", line 391, in ET
    endwaveno = convertor(start,"nm","cm-1")
  File "/home/seru/.local/lib/python3.10/site-packages/cclib/parser/utils.py", line 143, in convertor
    return _convertor[f"{fromunits}_to_{tounits}"](value)
KeyError: 'nm_to_cm-1'

During handling of the above exception, another exception occurred:

Thanks!

**Comment by rafaelpap** [comment]
I have made the following modifications to version 3.0.2: 
[gausssumgui.txt](https://github.com/gausssum/gausssum/files/13174287/gausssumgui.txt)
[plot.txt](https://github.com/gausssum/gausssum/files/13174289/plot.txt)
[electrontrans.txt](https://github.com/gausssum/gausssum/files/13174290/electrontrans.txt)
I am not sure all is ok but it works for me.
