### ISSUE TITLE
Error with electronic transitions

### ISSUE THREAD

**Issue by TheLittleField** [gausssum/gausssum#3]
I am attempting to visualize electronic transitions using a Gaussian log file however I have the following error:

`Traceback (most recent call last):
  File "D:\Tools\GaussSum\gausssum\src\gausssum\gausssumgui.py", line 415, in runscript
  File "D:\Tools\GaussSum\gausssum\src\gausssum\electrontrans.py", line 274, in ET
AttributeError: 'ccData_optdone_bool' object has no attribute 'filename'`

This error happens with almost every one of my log files, however a few have successfully produced the spectrum and I do not know why. I am running GaussSum 3.0.2 on Windows.

Thanks in advance

**Comment by baoilleach** [comment]
I don't know why either. Can you provide a small example log file? Please note that I can only fix bugs for public domain log files - are you happy to place the log file in the public domain?

**Comment by TheLittleField** [comment]
Sure here's an example file. Thanks

[Error log file.txt](https://github.com/gausssum/gausssum/files/2576657/Error.log.file.txt)

**Comment by TheLittleField** [comment]
any updates please?

**Comment by baoilleach** [comment]
Haven't had a chance to look at it yet. Why not have a look yourself?

**Comment by TheLittleField** [comment]
If I could do that, why would I be asking here? I will just use another program. Thank you so much!

**Comment by baoilleach** [comment]
I understand - it's just that my spare time is limited and I'm looking for new contributors. I will eventually sort it out, but it may be weeks or months before I do.
